# version: '3.8'

services:
  n8n:
    build: .
    image: n8n-custom
    ports:
      - "5678:5678"
    restart: always
    environment:
      - NODE_FUNCTION_ALLOW_EXTERNAL=*
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=securepassword
    volumes:
      - n8n_data:/home/node/.n8n  # Named volume for persistent storage

volumes:
  n8n_data:
